config/routes.rb
Rails.application.routes.draw do

  # get 'students/new'

  # get 'students/create'

  # get 'students/show'

  # get 'students/edit'

  # get 'students/update'

  # get 'students/destroy'

  root 'dojo#index'

  resources :dojo do
    resources :students
  end

end


# Prefix            Verb      URI Pattern                                Controller#Action
# ========================================================================================
# root              GET       /                                          dojo#index
# dojo_students     GET       /dojo/:dojo_id/students(.:format)          students#index
#                   POST      /dojo/:dojo_id/students(.:format)          students#create
# new_dojo_student  GET       /dojo/:dojo_id/students/new(.:format)      students#new
# edit_dojo_student GET       /dojo/:dojo_id/students/:id/edit(.:format) students#edit
# dojo_student      GET       /dojo/:dojo_id/students/:id(.:format)      students#show
#                   PATCH     /dojo/:dojo_id/students/:id(.:format)      students#update
#                   PUT       /dojo/:dojo_id/students/:id(.:format)      students#update
#                   DELETE    /dojo/:dojo_id/students/:id(.:format)      students#destroy
# dojo_index        GET       /dojo(.:format)                            dojo#index
#                   POST      /dojo(.:format)                            dojo#create
# new_dojo          GET       /dojo/new(.:format)                        dojo#new
# edit_dojo         GET       /dojo/:id/edit(.:format)                   dojo#edit
# dojo              GET       /dojo/:id(.:format)                        dojo#show
#                   PATCH     /dojo/:id(.:format)                        dojo#update
#                   PUT       /dojo/:id(.:format)                        dojo#update
#                   DELETE    /dojo/:id(.:format)                        dojo#destroy
# ========================================================================================

app/models/dojo.rb
class Dojo < ActiveRecord::Base
    has_many  :students, :dependent => :destroy
    validates :branch, :street, :city, :state, presence: true, length: { minimum: 2 }
    validates :branch, uniqueness: { case_sensitive: false }
end

app/controllers/dojo_controller.rb
class DojoController < ApplicationController

  before_action :set_dojo, only: [:show, :edit, :update, :destroy]

  # ============================================
  # GET Request - Renders root/home page [.html]
  # ============================================
  def index
    # --- [ Put in Session ]
    session[:page] = "dojo"
    # ---------------------
    @alldojos = Dojo.all
  end


  # =============================
  # GET Request - Renders [.html]
  # =============================
  def new
    # --- [ Put in Session ]
    session[:page] = "dojo"
    # ---------------------
    @dojo = Dojo.new
  end


  # ====================
  # POST Request [.html]
  # POST Request [.json]
  # ====================
  def create
    @dojo = Dojo.create(validate_params)
    # @dojo.valid?
    respond_to do |format|
      if @dojo.save
        format.html { redirect_to '/', notice: 'Dojo was successfully created.' }
        format.json { render :show, status: :created, location: @dojo }
      else
        format.html { render :new }
        format.json { render json: @dojo.errors, status: :unprocessable_entity }
      end
    end
  end


  # =============================
  # GET Request - Renders [.html]
  # =============================
  def show
    # --- [ Put in Session ]
    session[:page] = "dojo"
    # ---------------------
    @dojo = Dojo.find(params[:id])
    @students = @dojo.students.order(:last_name)
  end


  # =============================
  # GET Request - Renders [.html]
  # =============================
  def edit
    # --- [ Put in Session ]
    session[:page] = "dojo"
    # ---------------------
    @dojo = Dojo.find(params[:id])
    render "edit"
  end


  # =========================
  # PATCH/PUT Request [.html]
  # PATCH/PUT Request [.json]
  # =========================
  def update
    respond_to do |format|
      if @dojo.update(validate_params)
        format.html { redirect_to '/', notice: 'Dojo was successfully updated.' }
        format.json { render :show, status: :ok, location: @dojo }
      else
        format.html { render :edit }
        format.json { render json: @dojo.errors, status: :unprocessable_entity }
      end
    end
  end


  # ====================
  # DELETE /dojos/1
  # DELETE /dojos/1.json
  # ====================
  def destroy
    Dojo.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Dojo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dojo
      @dojo = Dojo.find(params[:id])
    end

    # Sanatizing/Validating Parameters...
    def validate_params
      params.require(:dojo).permit(:branch, :street, :city, :state)
    end
end

app/helpers/dojo_helper.rb
module DojoHelper
end

app/views/dojo/edit.html.erb
<!-- EDIT DOJO PAGE COMPONENT -->

<div class="container">

    <h2>Edit Dojo</h2>

    <div class="row">
    <form class="col s12 mt-4" action="/dojo/<%= @dojo.id %>" method="POST">
        <!--
        Error Display... if any
        -->
        <% if @dojo.errors.any? %>
        <div id="error_explanation">
            <h5>
                <span class="blue-text"><%= pluralize(@dojo.errors.count, "error") %></span>
                prohibited this dojo from being saved:
            </h5>
            <ul>
                <% @dojo.errors.full_messages.each do |message| %>
                <li class="red-text"><span class="blue-text right-margin1">&#187;</span><%= message %></li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <!--
        Form Requirements
        -->
        <input type="hidden" name="_method" value="patch">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <div class="row">
            <div class="input-field col s12">
                <input placeholder="" id="name" name="dojo[branch]" type="text" class="validate white-text" value="<%= @dojo.branch %>">
                <label for="name">Branch</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input placeholder="" id="name" name="dojo[street]" type="text" class="validate white-text" value="<%= @dojo.street %>">
                <label for="name">Street</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <input placeholder="" id="name" name="dojo[city]" type="text" class="validate white-text" value="<%= @dojo.city %>">
                <label for="name">City</label>
            </div>
            <div class="input-field col s6">
                <input placeholder="" id="name" name="dojo[state]" type="text" class="validate white-text" value="<%= @dojo.state %>">
                <label for="name">State</label>
            </div>
        </div>
        <button class="btn waves-effect sn" type="submit" name="action">Submit
            <i class="material-icons right blue-text">send</i>
        </button>
    </form> <!-- Form ends -->
    </div>  <!-- row ends -->
</div>  <!-- Container ends -->

app/views/dojo/index.html.erb
<div class="container">

    <% if notice %>
    <p id="notice"><%= notice %></p>
    <% end %>

    <h2>Listing <span class="white-text"><%= @alldojos.count %></span> Dojos</h2>

    <table class="highlight">
        <thead>
        <tr>
            <th class="theader">Coding Dojo Branch</th>
            <th class="theader">Street            </th>
            <th class="theader">City              </th>
            <th class="theader">State             </th>
            <th class="theader">Actions           </th>
        </tr>
        </thead>
        <tbody>
            <div>
                <% @alldojos.each do |dojo| %>
                <tr class="trbody">
                    <td><%= dojo.branch %></td>
                    <td><%= dojo.street %></td>
                    <td><%= dojo.city   %></td>
                    <td><%= dojo.state  %></td>
                    <td class="">
                        <a class="btn-small sn show" href="/dojo/<%= dojo.id %>"> Show</a>
                        <a class="btn-small sn edit" href="/dojo/<%= dojo.id %>/edit" %>Edit</a>
                        <form action="/dojo/<%= dojo.id %>" method="post">
                            <input type="hidden" name="_method" value="delete" />
                            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                            <input type="submit" value="Delete" class="btn-small sn delete">
                        </form>
                    </td>
                </tr>
                <% end %>
            </div>
        </tbody>
    </table>
</div>

<div class="row center-align">
    <div class="col s6">
    <!--
    Redirect to Create New Dojo Page
    -->
    <button class="btn sn top-margin1"><%= link_to 'New Dojo', new_dojo_url %></button>
    </div>
</div>

app/views/dojo/new.html.erb
<!-- ADD New DOJO PAGE COMPONENT -->

<div class="container">
    <h2>New Dojo</h2>
    <div class="row">
        <form class="col s12 mt-4" action="/dojo" method="POST">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
            <!--======================================================== [ Error Display... if any ]
            -->
            <% if @dojo.errors.any? %>
            <div id="error_explanation">
                <h5>
                    <span class="blue-text"><%= pluralize(@dojo.errors.count, "error") %></span>
                    prohibited this dojo from being saved:
                </h5>
                <ul>
                    <% @dojo.errors.full_messages.each do |message| %>
                    <li class="red-text"><span class="blue-text right-margin1">&#187;</span><%= message %></li>
                    <% end %>
                </ul>
            </div>
            <% end %>
            <!--
            =============================================================
            -->
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="" id="name" name="dojo[branch]" type="text" class="validate white-text">
                    <label for="name">Branch</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="" id="name" name="dojo[street]" type="text" class="validate white-text">
                    <label for="name">Street</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <input placeholder="" id="name" name="dojo[city]" type="text" class="validate white-text">
                    <label for="name">City</label>
                </div>
                <div class="input-field col s6">
                    <input placeholder="" id="name" name="dojo[state]" type="text" class="validate white-text">
                    <label for="name">State</label>
                </div>
            </div>
            <button class="btn waves-effect sn" type="submit" name="action">Submit
                <i class="material-icons right blue-text">send</i>
            </button>
        </form>
    </div>
</div>

app/views/dojo/show.html.erb
<div class="container">

    <% if notice %>
    <p id="notice"><%= notice %></p>
    <% end %>

    <h2><%= @dojo.branch %></h2>
    <ul class="col s12">
        <li class="col s6"><h6>Address: <b class="grey-text"><%= @dojo.street %></b></li></h6>
        <li class="col s6">
            <h6>City: <b class="grey-text"><%= @dojo.city   %></b></h6>
            <h6>State: <b class="grey-text"><%= @dojo.state  %></b></h6>
        </li>
    </ul>

    <table class="highlight">
        <thead>
        <tr>
            <th class="theader">First Name</th>
            <th class="theader">Last Name </th>
            <th class="theader">Email     </th>
            <th class="theader">Actions   </th>
        </tr>
        </thead>
        <tbody>
            <div>
                <% @students.each do |student| %>
                <tr class="trbody">
                    <td><%= student.first_name %></td>
                    <td><%= student.last_name  %></td>
                    <td><%= student.email      %></td>
                    <td class="">
                        <a class="btn-small sn show" href="/dojo/<%= @dojo.id %>/students/<%= student.id %>"> Show</a>
                        <a class="btn-small sn edit" href="/dojo/<%= @dojo.id %>/students/<%= student.id %>/edit" %>Edit</a>
                        <form action="/dojo/<%= @dojo.id %>/students/<%= student.id %>" method="post">
                            <input type="hidden" name="_method" value="delete" />
                            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                            <input type="submit" value="Delete" class="btn-small sn delete">
                        </form>
                    </td>
                </tr>
                <% end %>
            </div>
        </tbody>
    </table>
</div>

<div class="row center-align">
    <div class="col s6">
    <!--
    Redirect to Create New Student Page
    -->
    <button class="btn sn top-margin1 left-margin2"><%= link_to 'New Student', new_dojo_student_url(@dojo) %></button>
    <!--<a class="btn sn top-margin1" href="/dojo/<%= @dojo.id %>/students/new" %>New Student</a>-->
    </div>
</div>